title: Semih Desticioglu # your name (or website title) here
logo: "/images/semihdest.jpg?raw=true" # your photo (or logo) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc in Data Science, Sabanci University.
  Senior Expert Data Analyst at Turkcell Technology.
  
  <br><br>
  Skills: Python, SQL, PL/SQL, Machine Learning, Data Science, Web Scraping, Data Analysis, Data Modelling, HTML/CSS
  <br><br>
  <a href="https://www.linkedin.com/in/semihdesticioglu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
