title: Semih Desticioğlu # your name (or website title) here
logo: "/images/IMG-5430 - Copy.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I'm a Data Analyst with Data Science Master Degree who loves dealing with data. I love doing data analysis projects and creating products with data. I have bussines units experience on sales and stock planning in technology retail.
Skills: Python, SQL, PL/SQL, Machine Learning, Data Science, Web Scraping, Data Analysis, Data Modelling, HTML/CSS
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/semihdesticioglu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
